name: Astronomer CI - Deploy code (Multiple Branches)

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deployment-type:
    runs-on: ubuntu-latest
    outputs:
      DAGS_ONLY: ${{ steps.deployment-type.outputs.DAGS_ONLY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2  # Updated to version 2

      - name: Get Deployment Type
        id: deployment-type
        run: |
          files=$(git diff --name-only HEAD^..HEAD)
          dags_only=1

          for file in $files; do
            if [[ $file != "dags/"* ]]; then
              echo "$file is not a dag, triggering a full image build"
              dags_only=0
              break
            fi
          done

          echo "DAGS_ONLY=$dags_only" >> $GITHUB_ENV  # Updated to $GITHUB_ENV

  dev-push:
    if: github.ref == 'refs/heads/dev'
    env:
      ## Sets DEV Deployment API key credentials as environment variables
      ASTRONOMER_KEY_ID: ${{ secrets.DEV_ASTRONOMER_KEY_ID }}
      ASTRONOMER_KEY_SECRET: ${{ secrets.DEV_ASTRONOMER_KEY_SECRET }}
    runs-on: ubuntu-latest
    needs: deployment-type
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2  # Updated to version 2

      # If only DAGs changed, do a DAG Deploy
      - name: DAG Deploy to Astro
        if: needs.deployment-type.outputs.DAGS_ONLY == 1
        run: |
          curl -sSL https://install.astronomer.io | sudo bash -s - v1.18.2
          astro deployment update --dag-deploy enable --force
          astro deploy --dags

      # If any other files changed, do a regular Deploy
      - name: Image and DAG Deploy to Astro
        if: needs.deployment-type.outputs.DAGS_ONLY == 0
        run: |
          curl -sSL https://install.astronomer.io | sudo bash -s - v1.18.2
          astro deploy

  prod-push:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    env:
      ## Sets PROD Deployment API key credentials as environment variables
      ASTRONOMER_KEY_ID: ${{ secrets.PROD_ASTRONOMER_KEY_ID }}
      ASTRONOMER_KEY_SECRET: ${{ secrets.PROD_ASTRONOMER_KEY_SECRET }}
    runs-on: ubuntu-latest
    needs: deployment-type
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2  # Updated to version 2

      # If only DAGs changed, do a DAG Deploy
      - name: DAG Deploy to Astro
        if: needs.deployment-type.outputs.DAGS_ONLY == 1
        run: |
          curl -sSL https://install.astronomer.io | sudo bash -s -- v1.18.2
          astro deployment update --dag-deploy enable --force
          astro deploy --dags

      # If any other files changed, do a regular Deploy
      - name: Image and DAG Deploy to Astro
        if: needs.deployment-type.outputs.DAGS_ONLY == 0
        run: |
          curl -sSL https://install.astronomer.io | sudo bash -s -- v1.18.2
          astro deploy
